wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    code_path: code/examples/pytorch_cifar10_resnet.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.4
      5: 0.10.22
      8:
      - 5
base_lr:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 1024
batches_per_allreduce:
  desc: null
  value: 1
cuda:
  desc: null
  value: true
damping:
  desc: null
  value: 0.003
damping_alpha:
  desc: null
  value: 0.5
damping_schedule:
  desc: null
  value: null
diag_blocks:
  desc: null
  value: 1
diag_warmup:
  desc: null
  value: 5
dir:
  desc: null
  value: /datasets/cifar10
distribute_layer_factors:
  desc: null
  value: false
epochs:
  desc: null
  value: 100
fp16_allreduce:
  desc: null
  value: false
kfac_cov_update_freq:
  desc: null
  value: 1
kfac_name:
  desc: null
  value: inverse
kfac_update_freq:
  desc: null
  value: 0
kfac_update_freq_alpha:
  desc: null
  value: 10
kfac_update_freq_schedule:
  desc: null
  value: null
kl_clip:
  desc: null
  value: 0.001
log_dir:
  desc: null
  value: ./logs
lr_decay:
  desc: null
  value:
  - 35
  - 75
  - 90
model:
  desc: null
  value: resnet32
momentum:
  desc: null
  value: 0.9
no_cuda:
  desc: null
  value: false
seed:
  desc: null
  value: 42
sparse_ratio:
  desc: null
  value: 1.0
stat_decay:
  desc: null
  value: 0.95
test_batch_size:
  desc: null
  value: 128
warmup_epochs:
  desc: null
  value: 5
weight_decay:
  desc: null
  value: 0.0005
